# Generated by Django 5.2.7 on 2025-10-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
