# Generated by Django 5.2.7 on 2025-10-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_github_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='api.entry'),
        ),
    ]
