# Generated by Django 5.2.7 on 2025-10-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_entry_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='followers',
        ),
    ]
