# Generated by Django 5.2.7 on 2025-10-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_entry_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='api.entry'),
        ),
    ]
