# Generated by Django 5.2.7 on 2025-10-18 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_entry_following_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follwers',
            field=models.ManyToManyField(related_name='following_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
