# Generated by Django 5.2.7 on 2025-10-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_description_user_name_alter_user_github_and_more'),
        ('api', '0009_user_follwers'),
    ]

    operations = [
    ]
