# Generated by Django 5.2.7 on 2025-10-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comment_commentlike_entrylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
