# Generated by Django 5.2.7 on 2025-10-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_entry_comment_count_entry_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_etag',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='latest_github_event_id',
            field=models.CharField(default=''),
        ),
    ]
