# Generated by Django 5.2.7 on 2025-10-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_github_etag_user_latest_github_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_etag',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='latest_github_event_id',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
