# Generated by Django 5.2.7 on 2025-10-31 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_is_active'),
        ('api', '0014_alter_user_description_alter_user_github_etag_and_more'),
    ]

    operations = [
    ]
