# Generated by Django 5.2.7 on 2025-11-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.CharField(default='', max_length=255),
        ),
    ]
