# Generated by Django 5.2.7 on 2025-11-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fqid',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
