# Generated by Django 5.2.7 on 2025-11-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_entry_description_user_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fqid',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='fqid',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
