# Generated by Django 5.2.7 on 2025-11-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_entry_description_user_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='url',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
