# Generated by Django 5.2.7 on 2025-11-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_comment_fqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='fqid',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
