# Generated by Django 5.2.7 on 2025-11-12 09:45

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_comment_fqid_entry_fqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fqid',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.CharField(db_index=True, default=api.models.generate_id, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('fqid', models.URLField(blank=True, null=True, unique=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='api.comment')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='api.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'entry')},
            },
        ),
    ]
