# Generated by Django 5.2.7 on 2025-11-14 15:20

from django.db import migrations

def get_url_helper():
    from django.conf import settings
    if hasattr(settings, 'DJANGO_ENV'):
        if settings.DJANGO_ENV == 'development':
            return "http://127.0.0.1:8000/"
        elif settings.DJANGO_ENV == 'production':
            return ""
    return "http://127.0.0.1:8000/"

def populate_entry_urls(apps, schema_editor):
    Entry = apps.get_model('api', 'Entry')
    base_url = get_url_helper()
    
    for entry in Entry.objects.all():
        entry.url = f"{base_url}api/authors/{entry.author_id}/entries/{entry.id}"
        entry.save(update_fields=['url'])

def reverse_populate(apps, schema_editor):
    Entry = apps.get_model('api', 'Entry')
    Entry.objects.all().update(url="")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_entry_url'),  
    ]

    operations = [
        migrations.RunPython(populate_entry_urls, reverse_populate),
    ]
