# Generated by Django 5.2.7 on 2025-11-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_populate_entry_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
    ]
