# Generated by Django 5.2.7 on 2025-11-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_fqid_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
