# Generated by Django 5.2.7 on 2025-11-16 04:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_entry_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.CharField(db_index=True, default=api.models.generate_id, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('token', models.CharField(default='', max_length=255)),
                ('is_connected', models.BooleanField()),
            ],
        ),
    ]
